
def email(people):
    for index in people:
        print("name : {}  email : <{}@gmail.com>".format(index , index))


email(["james" , "jeff" , "jason" , "jessica" , "jeff" , "jason" , "jessica" , "james" , "ashley" , "moeez"])

print("\n")
print("\n")
print("\n")

def email2(people):
    new_list = []
    for index , person in enumerate(people):
        new_list.append("name : {}  email : <{}@gmail.com>".format(person , person))
    return new_list


print("\n")
print("appended list with out enumeration:")

print(email2(["james" , "jeff" , "jason" , "jessica" , "jeff" , "jason" , "jessica" , "james" , "ashley" , "moeez"]))

new_list2 = email2(["james" , "jeff" , "jason" , "jessica" , "jeff" , "jason" , "jessica" , "james" , "ashley" , "moeez"])


print("\n")
print("\n")
print("\n")

print("enumrating the list that was generated by the email function")
print("\n")


for index , people in enumerate(new_list2):
    print("{} , {}".format(index + 1 , people))
