filenames = ["program.c", "stdio.hpp", "sample.hpp", "a.out", "math.hpp", "hpp.out"]

print(sorted(filenames, key=lambda x: x.lower()))

    #replace .c with .h
    #replace .hpp with .h
    #replace .out with .h

newfilenames = []

for words in filenames:
    if words.endswith(".c"):
        newfilenames.append(words[:-2] + ".h")
    elif words.endswith(".hpp"):
        newfilenames.append(words[:-4] + ".h")
    elif words.endswith(".out"):
        newfilenames.append(words[:-4] + ".h")

# make a list of words generated by the above code
print(newfilenames)
